/*
 * grafeas.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The type of an alias.   - KIND_UNSPECIFIED: Unknown.  - FIXED: Git tag.  - MOVABLE: Git branch.  - OTHER: Used to specify non-standard aliases. For example, if a Git repo has a ref named \&quot;refs/foo/bar\&quot;.
 */
@JsonAdapter(AliasContextKind.Adapter.class)
public enum AliasContextKind {
  
  KIND_UNSPECIFIED("KIND_UNSPECIFIED"),
  
  FIXED("FIXED"),
  
  MOVABLE("MOVABLE"),
  
  OTHER("OTHER");

  private String value;

  AliasContextKind(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AliasContextKind fromValue(String text) {
    for (AliasContextKind b : AliasContextKind.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<AliasContextKind> {
    @Override
    public void write(final JsonWriter jsonWriter, final AliasContextKind enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AliasContextKind read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AliasContextKind.fromValue(String.valueOf(value));
    }
  }
}

