/*
 * grafeas.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets CVSSv3AttackVector
 */
@JsonAdapter(CVSSv3AttackVector.Adapter.class)
public enum CVSSv3AttackVector {
  
  UNSPECIFIED("ATTACK_VECTOR_UNSPECIFIED"),
  
  NETWORK("ATTACK_VECTOR_NETWORK"),
  
  ADJACENT("ATTACK_VECTOR_ADJACENT"),
  
  LOCAL("ATTACK_VECTOR_LOCAL"),
  
  PHYSICAL("ATTACK_VECTOR_PHYSICAL");

  private String value;

  CVSSv3AttackVector(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CVSSv3AttackVector fromValue(String text) {
    for (CVSSv3AttackVector b : CVSSv3AttackVector.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<CVSSv3AttackVector> {
    @Override
    public void write(final JsonWriter jsonWriter, final CVSSv3AttackVector enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CVSSv3AttackVector read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CVSSv3AttackVector.fromValue(String.valueOf(value));
    }
  }
}

