/*
 * grafeas.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets CVSSv3UserInteraction
 */
@JsonAdapter(CVSSv3UserInteraction.Adapter.class)
public enum CVSSv3UserInteraction {
  
  UNSPECIFIED("USER_INTERACTION_UNSPECIFIED"),
  
  NONE("USER_INTERACTION_NONE"),
  
  REQUIRED("USER_INTERACTION_REQUIRED");

  private String value;

  CVSSv3UserInteraction(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CVSSv3UserInteraction fromValue(String text) {
    for (CVSSv3UserInteraction b : CVSSv3UserInteraction.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<CVSSv3UserInteraction> {
    @Override
    public void write(final JsonWriter jsonWriter, final CVSSv3UserInteraction enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CVSSv3UserInteraction read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CVSSv3UserInteraction.fromValue(String.valueOf(value));
    }
  }
}

