/*
 * grafeas.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.V1beta1packageLocation;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * This represents how a particular software package may be installed on a system.
 */
@ApiModel(description = "This represents how a particular software package may be installed on a system.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-22T18:45:44.983-04:00")
public class PackageInstallation {
  @SerializedName("name")
  private String name = null;

  @SerializedName("location")
  private List<V1beta1packageLocation> location = null;

   /**
   * Output only. The name of the installed package.
   * @return name
  **/
  @ApiModelProperty(value = "Output only. The name of the installed package.")
  public String getName() {
    return name;
  }

  public PackageInstallation location(List<V1beta1packageLocation> location) {
    this.location = location;
    return this;
  }

  public PackageInstallation addLocationItem(V1beta1packageLocation locationItem) {
    if (this.location == null) {
      this.location = new ArrayList<V1beta1packageLocation>();
    }
    this.location.add(locationItem);
    return this;
  }

   /**
   * Required. All of the places within the filesystem versions of this package have been found.
   * @return location
  **/
  @ApiModelProperty(value = "Required. All of the places within the filesystem versions of this package have been found.")
  public List<V1beta1packageLocation> getLocation() {
    return location;
  }

  public void setLocation(List<V1beta1packageLocation> location) {
    this.location = location;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageInstallation packageInstallation = (PackageInstallation) o;
    return Objects.equals(this.name, packageInstallation.name) &&
        Objects.equals(this.location, packageInstallation.location);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, location);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackageInstallation {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

