/*
 * grafeas.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Instruction set architectures supported by various package managers.   - ARCHITECTURE_UNSPECIFIED: Unknown architecture.  - X86: X86 architecture.  - X64: X64 architecture.
 */
@JsonAdapter(PackageArchitecture.Adapter.class)
public enum PackageArchitecture {
  
  ARCHITECTURE_UNSPECIFIED("ARCHITECTURE_UNSPECIFIED"),
  
  X86("X86"),
  
  X64("X64");

  private String value;

  PackageArchitecture(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PackageArchitecture fromValue(String text) {
    for (PackageArchitecture b : PackageArchitecture.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PackageArchitecture> {
    @Override
    public void write(final JsonWriter jsonWriter, final PackageArchitecture enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PackageArchitecture read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PackageArchitecture.fromValue(String.valueOf(value));
    }
  }
}

