/*
 * grafeas.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PackageInstallation;
import java.io.IOException;

/**
 * Details of a package occurrence.
 */
@ApiModel(description = "Details of a package occurrence.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-22T18:45:44.983-04:00")
public class V1beta1packageDetails {
  @SerializedName("installation")
  private PackageInstallation installation = null;

  public V1beta1packageDetails installation(PackageInstallation installation) {
    this.installation = installation;
    return this;
  }

   /**
   * Required. Where the package was installed.
   * @return installation
  **/
  @ApiModelProperty(value = "Required. Where the package was installed.")
  public PackageInstallation getInstallation() {
    return installation;
  }

  public void setInstallation(PackageInstallation installation) {
    this.installation = installation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1packageDetails v1beta1packageDetails = (V1beta1packageDetails) o;
    return Objects.equals(this.installation, v1beta1packageDetails.installation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(installation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1packageDetails {\n");
    
    sb.append("    installation: ").append(toIndentedString(installation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

