/*
 * grafeas.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Whether this is an ordinary package version or a sentinel MIN/MAX version.   - VERSION_KIND_UNSPECIFIED: Unknown.  - NORMAL: A standard package version.  - MINIMUM: A special version representing negative infinity.  - MAXIMUM: A special version representing positive infinity.
 */
@JsonAdapter(VersionVersionKind.Adapter.class)
public enum VersionVersionKind {
  
  VERSION_KIND_UNSPECIFIED("VERSION_KIND_UNSPECIFIED"),
  
  NORMAL("NORMAL"),
  
  MINIMUM("MINIMUM"),
  
  MAXIMUM("MAXIMUM");

  private String value;

  VersionVersionKind(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static VersionVersionKind fromValue(String text) {
    for (VersionVersionKind b : VersionVersionKind.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<VersionVersionKind> {
    @Override
    public void write(final JsonWriter jsonWriter, final VersionVersionKind enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public VersionVersionKind read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return VersionVersionKind.fromValue(String.valueOf(value));
    }
  }
}

