/*
 * grafeas.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * WindowsDetailKnowledgeBase
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-22T18:45:44.983-04:00")
public class WindowsDetailKnowledgeBase {
  @SerializedName("name")
  private String name = null;

  @SerializedName("url")
  private String url = null;

  public WindowsDetailKnowledgeBase name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The KB name (generally of the form KB[0-9]+ i.e. KB123456).
   * @return name
  **/
  @ApiModelProperty(value = "The KB name (generally of the form KB[0-9]+ i.e. KB123456).")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public WindowsDetailKnowledgeBase url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WindowsDetailKnowledgeBase windowsDetailKnowledgeBase = (WindowsDetailKnowledgeBase) o;
    return Objects.equals(this.name, windowsDetailKnowledgeBase.name) &&
        Objects.equals(this.url, windowsDetailKnowledgeBase.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WindowsDetailKnowledgeBase {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

