/*
 * Grafeas API
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.grafeas.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.grafeas.model.ApiBuildSignature;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Note holding the version of the provider&#39;s builder and the signature of the provenance message in linked BuildDetails.
 */
@ApiModel(description = "Note holding the version of the provider's builder and the signature of the provenance message in linked BuildDetails.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-04T13:20:14.121-07:00")
public class ApiBuildType {
  @SerializedName("builder_version")
  private String builderVersion = null;

  @SerializedName("signature")
  private ApiBuildSignature signature = null;

  public ApiBuildType builderVersion(String builderVersion) {
    this.builderVersion = builderVersion;
    return this;
  }

   /**
   * Version of the builder which produced this Note.
   * @return builderVersion
  **/
  @ApiModelProperty(value = "Version of the builder which produced this Note.")
  public String getBuilderVersion() {
    return builderVersion;
  }

  public void setBuilderVersion(String builderVersion) {
    this.builderVersion = builderVersion;
  }

  public ApiBuildType signature(ApiBuildSignature signature) {
    this.signature = signature;
    return this;
  }

   /**
   * Signature of the build in Occurrences pointing to the Note containing this &#x60;BuilderDetails&#x60;.
   * @return signature
  **/
  @ApiModelProperty(value = "Signature of the build in Occurrences pointing to the Note containing this `BuilderDetails`.")
  public ApiBuildSignature getSignature() {
    return signature;
  }

  public void setSignature(ApiBuildSignature signature) {
    this.signature = signature;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiBuildType apiBuildType = (ApiBuildType) o;
    return Objects.equals(this.builderVersion, apiBuildType.builderVersion) &&
        Objects.equals(this.signature, apiBuildType.signature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(builderVersion, signature);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiBuildType {\n");
    
    sb.append("    builderVersion: ").append(toIndentedString(builderVersion)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

