/*
 * Grafeas API
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.grafeas.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.grafeas.model.BuildSignatureKeyType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Message encapsulating the signature of the verified build.
 */
@ApiModel(description = "Message encapsulating the signature of the verified build.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-04T13:20:14.121-07:00")
public class ApiBuildSignature {
  @SerializedName("public_key")
  private String publicKey = null;

  @SerializedName("signature")
  private String signature = null;

  @SerializedName("key_id")
  private String keyId = null;

  @SerializedName("key_type")
  private BuildSignatureKeyType keyType = null;

  public ApiBuildSignature publicKey(String publicKey) {
    this.publicKey = publicKey;
    return this;
  }

   /**
   * Public key of the builder which can be used to verify that the related findings are valid and unchanged. If &#x60;key_type&#x60; is empty, this defaults to PEM encoded public keys.  This field may be empty if &#x60;key_id&#x60; references an external key.  For Cloud Container Builder based signatures, this is a PEM encoded public key. To verify the Cloud Container Builder signature, place the contents of this field into a file (public.pem). The signature field is base64-decoded into its binary representation in signature.bin, and the provenance bytes from &#x60;BuildDetails&#x60; are base64-decoded into a binary representation in signed.bin. OpenSSL can then verify the signature: &#x60;openssl sha256 -verify public.pem -signature signature.bin signed.bin&#x60;
   * @return publicKey
  **/
  @ApiModelProperty(value = "Public key of the builder which can be used to verify that the related findings are valid and unchanged. If `key_type` is empty, this defaults to PEM encoded public keys.  This field may be empty if `key_id` references an external key.  For Cloud Container Builder based signatures, this is a PEM encoded public key. To verify the Cloud Container Builder signature, place the contents of this field into a file (public.pem). The signature field is base64-decoded into its binary representation in signature.bin, and the provenance bytes from `BuildDetails` are base64-decoded into a binary representation in signed.bin. OpenSSL can then verify the signature: `openssl sha256 -verify public.pem -signature signature.bin signed.bin`")
  public String getPublicKey() {
    return publicKey;
  }

  public void setPublicKey(String publicKey) {
    this.publicKey = publicKey;
  }

  public ApiBuildSignature signature(String signature) {
    this.signature = signature;
    return this;
  }

   /**
   * Signature of the related &#x60;BuildProvenance&#x60;, encoded in a base64 string.
   * @return signature
  **/
  @ApiModelProperty(value = "Signature of the related `BuildProvenance`, encoded in a base64 string.")
  public String getSignature() {
    return signature;
  }

  public void setSignature(String signature) {
    this.signature = signature;
  }

  public ApiBuildSignature keyId(String keyId) {
    this.keyId = keyId;
    return this;
  }

   /**
   * An Id for the key used to sign. This could be either an Id for the key stored in &#x60;public_key&#x60; (such as the Id or fingerprint for a PGP key, or the CN for a cert), or a reference to an external key (such as a reference to a key in Cloud Key Management Service).
   * @return keyId
  **/
  @ApiModelProperty(value = "An Id for the key used to sign. This could be either an Id for the key stored in `public_key` (such as the Id or fingerprint for a PGP key, or the CN for a cert), or a reference to an external key (such as a reference to a key in Cloud Key Management Service).")
  public String getKeyId() {
    return keyId;
  }

  public void setKeyId(String keyId) {
    this.keyId = keyId;
  }

  public ApiBuildSignature keyType(BuildSignatureKeyType keyType) {
    this.keyType = keyType;
    return this;
  }

   /**
   * Get keyType
   * @return keyType
  **/
  @ApiModelProperty(value = "")
  public BuildSignatureKeyType getKeyType() {
    return keyType;
  }

  public void setKeyType(BuildSignatureKeyType keyType) {
    this.keyType = keyType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiBuildSignature apiBuildSignature = (ApiBuildSignature) o;
    return Objects.equals(this.publicKey, apiBuildSignature.publicKey) &&
        Objects.equals(this.signature, apiBuildSignature.signature) &&
        Objects.equals(this.keyId, apiBuildSignature.keyId) &&
        Objects.equals(this.keyType, apiBuildSignature.keyType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(publicKey, signature, keyId, keyType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiBuildSignature {\n");
    
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    keyId: ").append(toIndentedString(keyId)).append("\n");
    sb.append("    keyType: ").append(toIndentedString(keyType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

