/*
 * Grafeas API
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.grafeas.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.grafeas.model.ApiOccurrence;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Response including listed occurrences for a note.
 */
@ApiModel(description = "Response including listed occurrences for a note.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-04T13:20:14.121-07:00")
public class ApiListNoteOccurrencesResponse {
  @SerializedName("occurrences")
  private List<ApiOccurrence> occurrences = null;

  @SerializedName("next_page_token")
  private String nextPageToken = null;

  public ApiListNoteOccurrencesResponse occurrences(List<ApiOccurrence> occurrences) {
    this.occurrences = occurrences;
    return this;
  }

  public ApiListNoteOccurrencesResponse addOccurrencesItem(ApiOccurrence occurrencesItem) {
    if (this.occurrences == null) {
      this.occurrences = new ArrayList<ApiOccurrence>();
    }
    this.occurrences.add(occurrencesItem);
    return this;
  }

   /**
   * The occurrences attached to the specified note.
   * @return occurrences
  **/
  @ApiModelProperty(value = "The occurrences attached to the specified note.")
  public List<ApiOccurrence> getOccurrences() {
    return occurrences;
  }

  public void setOccurrences(List<ApiOccurrence> occurrences) {
    this.occurrences = occurrences;
  }

  public ApiListNoteOccurrencesResponse nextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

   /**
   * Token to receive the next page of notes.
   * @return nextPageToken
  **/
  @ApiModelProperty(value = "Token to receive the next page of notes.")
  public String getNextPageToken() {
    return nextPageToken;
  }

  public void setNextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiListNoteOccurrencesResponse apiListNoteOccurrencesResponse = (ApiListNoteOccurrencesResponse) o;
    return Objects.equals(this.occurrences, apiListNoteOccurrencesResponse.occurrences) &&
        Objects.equals(this.nextPageToken, apiListNoteOccurrencesResponse.nextPageToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(occurrences, nextPageToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiListNoteOccurrencesResponse {\n");
    
    sb.append("    occurrences: ").append(toIndentedString(occurrences)).append("\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

