/*
 * Grafeas API
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.grafeas.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.grafeas.model.ApiProject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApiListProjectsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-04T13:20:14.121-07:00")
public class ApiListProjectsResponse {
  @SerializedName("projects")
  private List<ApiProject> projects = null;

  @SerializedName("next_page_token")
  private String nextPageToken = null;

  public ApiListProjectsResponse projects(List<ApiProject> projects) {
    this.projects = projects;
    return this;
  }

  public ApiListProjectsResponse addProjectsItem(ApiProject projectsItem) {
    if (this.projects == null) {
      this.projects = new ArrayList<ApiProject>();
    }
    this.projects.add(projectsItem);
    return this;
  }

   /**
   * The projects requested.
   * @return projects
  **/
  @ApiModelProperty(value = "The projects requested.")
  public List<ApiProject> getProjects() {
    return projects;
  }

  public void setProjects(List<ApiProject> projects) {
    this.projects = projects;
  }

  public ApiListProjectsResponse nextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

   /**
   * The next pagination token in the list response. It should be used as &#x60;page_token&#x60; for the following request. An empty value means no more results.
   * @return nextPageToken
  **/
  @ApiModelProperty(value = "The next pagination token in the list response. It should be used as `page_token` for the following request. An empty value means no more results.")
  public String getNextPageToken() {
    return nextPageToken;
  }

  public void setNextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiListProjectsResponse apiListProjectsResponse = (ApiListProjectsResponse) o;
    return Objects.equals(this.projects, apiListProjectsResponse.projects) &&
        Objects.equals(this.nextPageToken, apiListProjectsResponse.nextPageToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projects, nextPageToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiListProjectsResponse {\n");
    
    sb.append("    projects: ").append(toIndentedString(projects)).append("\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

