/*
 * Grafeas API
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.grafeas.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * This must be 1:1 with members of our oneofs, it can be used for filtering Note and Occurrence on their kind.   - KIND_UNSPECIFIED: Unknown  - PACKAGE_VULNERABILITY: The note and occurrence represent a package vulnerability.  - BUILD_DETAILS: The note and occurrence assert build provenance.  - IMAGE_BASIS: This represents an image basis relationship.  - PACKAGE_MANAGER: This represents a package installed via a package manager.  - DEPLOYABLE: The note and occurrence track deployment events.  - DISCOVERY: The note and occurrence track the initial discovery status of a resource.  - ATTESTATION_AUTHORITY: This represents a logical \&quot;role\&quot; that can attest to artifacts.
 */
@JsonAdapter(ApiNoteKind.Adapter.class)
public enum ApiNoteKind {
  
  KIND_UNSPECIFIED("KIND_UNSPECIFIED"),
  
  PACKAGE_VULNERABILITY("PACKAGE_VULNERABILITY"),
  
  BUILD_DETAILS("BUILD_DETAILS"),
  
  IMAGE_BASIS("IMAGE_BASIS"),
  
  PACKAGE_MANAGER("PACKAGE_MANAGER"),
  
  DEPLOYABLE("DEPLOYABLE"),
  
  DISCOVERY("DISCOVERY"),
  
  ATTESTATION_AUTHORITY("ATTESTATION_AUTHORITY");

  private String value;

  ApiNoteKind(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ApiNoteKind fromValue(String text) {
    for (ApiNoteKind b : ApiNoteKind.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ApiNoteKind> {
    @Override
    public void write(final JsonWriter jsonWriter, final ApiNoteKind enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ApiNoteKind read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ApiNoteKind.fromValue(String.valueOf(value));
    }
  }
}

