/*
 * Grafeas API
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.grafeas.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.grafeas.model.ApiPgpSignedAttestation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AttestationAuthorityAttestationDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-04T13:20:14.121-07:00")
public class AttestationAuthorityAttestationDetails {
  @SerializedName("pgp_signed_attestation")
  private ApiPgpSignedAttestation pgpSignedAttestation = null;

  public AttestationAuthorityAttestationDetails pgpSignedAttestation(ApiPgpSignedAttestation pgpSignedAttestation) {
    this.pgpSignedAttestation = pgpSignedAttestation;
    return this;
  }

   /**
   * Get pgpSignedAttestation
   * @return pgpSignedAttestation
  **/
  @ApiModelProperty(value = "")
  public ApiPgpSignedAttestation getPgpSignedAttestation() {
    return pgpSignedAttestation;
  }

  public void setPgpSignedAttestation(ApiPgpSignedAttestation pgpSignedAttestation) {
    this.pgpSignedAttestation = pgpSignedAttestation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttestationAuthorityAttestationDetails attestationAuthorityAttestationDetails = (AttestationAuthorityAttestationDetails) o;
    return Objects.equals(this.pgpSignedAttestation, attestationAuthorityAttestationDetails.pgpSignedAttestation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pgpSignedAttestation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttestationAuthorityAttestationDetails {\n");
    
    sb.append("    pgpSignedAttestation: ").append(toIndentedString(pgpSignedAttestation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

