/*
 * Grafeas API
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.grafeas.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Types of platforms.   - PLATFORM_UNSPECIFIED: Unknown  - GKE: Google Container Engine  - FLEX: Google App Engine: Flexible Environment  - CUSTOM: Custom user-defined platform
 */
@JsonAdapter(DeploymentDetailsPlatform.Adapter.class)
public enum DeploymentDetailsPlatform {
  
  PLATFORM_UNSPECIFIED("PLATFORM_UNSPECIFIED"),
  
  GKE("GKE"),
  
  FLEX("FLEX"),
  
  CUSTOM("CUSTOM");

  private String value;

  DeploymentDetailsPlatform(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DeploymentDetailsPlatform fromValue(String text) {
    for (DeploymentDetailsPlatform b : DeploymentDetailsPlatform.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<DeploymentDetailsPlatform> {
    @Override
    public void write(final JsonWriter jsonWriter, final DeploymentDetailsPlatform enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DeploymentDetailsPlatform read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DeploymentDetailsPlatform.fromValue(String.valueOf(value));
    }
  }
}

