/*
 * Grafeas API
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.grafeas.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.grafeas.model.DeploymentDetailsPlatform;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * The period during which some deployable was active in a runtime.
 */
@ApiModel(description = "The period during which some deployable was active in a runtime.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-04T13:20:14.121-07:00")
public class DeployableDeploymentDetails {
  @SerializedName("user_email")
  private String userEmail = null;

  @SerializedName("deploy_time")
  private OffsetDateTime deployTime = null;

  @SerializedName("undeploy_time")
  private OffsetDateTime undeployTime = null;

  @SerializedName("config")
  private String config = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("resource_uri")
  private List<String> resourceUri = null;

  @SerializedName("platform")
  private DeploymentDetailsPlatform platform = null;

  public DeployableDeploymentDetails userEmail(String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

   /**
   * Identity of the user that triggered this deployment.
   * @return userEmail
  **/
  @ApiModelProperty(value = "Identity of the user that triggered this deployment.")
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public DeployableDeploymentDetails deployTime(OffsetDateTime deployTime) {
    this.deployTime = deployTime;
    return this;
  }

   /**
   * Beginning of the lifetime of this deployment.
   * @return deployTime
  **/
  @ApiModelProperty(value = "Beginning of the lifetime of this deployment.")
  public OffsetDateTime getDeployTime() {
    return deployTime;
  }

  public void setDeployTime(OffsetDateTime deployTime) {
    this.deployTime = deployTime;
  }

  public DeployableDeploymentDetails undeployTime(OffsetDateTime undeployTime) {
    this.undeployTime = undeployTime;
    return this;
  }

   /**
   * End of the lifetime of this deployment.
   * @return undeployTime
  **/
  @ApiModelProperty(value = "End of the lifetime of this deployment.")
  public OffsetDateTime getUndeployTime() {
    return undeployTime;
  }

  public void setUndeployTime(OffsetDateTime undeployTime) {
    this.undeployTime = undeployTime;
  }

  public DeployableDeploymentDetails config(String config) {
    this.config = config;
    return this;
  }

   /**
   * Configuration used to create this deployment.
   * @return config
  **/
  @ApiModelProperty(value = "Configuration used to create this deployment.")
  public String getConfig() {
    return config;
  }

  public void setConfig(String config) {
    this.config = config;
  }

  public DeployableDeploymentDetails address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Address of the runtime element hosting this deployment.
   * @return address
  **/
  @ApiModelProperty(value = "Address of the runtime element hosting this deployment.")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public DeployableDeploymentDetails resourceUri(List<String> resourceUri) {
    this.resourceUri = resourceUri;
    return this;
  }

  public DeployableDeploymentDetails addResourceUriItem(String resourceUriItem) {
    if (this.resourceUri == null) {
      this.resourceUri = new ArrayList<String>();
    }
    this.resourceUri.add(resourceUriItem);
    return this;
  }

   /**
   * Output only. Resource URI for the artifact being deployed taken from the deployable field with the same name.
   * @return resourceUri
  **/
  @ApiModelProperty(value = "Output only. Resource URI for the artifact being deployed taken from the deployable field with the same name.")
  public List<String> getResourceUri() {
    return resourceUri;
  }

  public void setResourceUri(List<String> resourceUri) {
    this.resourceUri = resourceUri;
  }

  public DeployableDeploymentDetails platform(DeploymentDetailsPlatform platform) {
    this.platform = platform;
    return this;
  }

   /**
   * Platform hosting this deployment.
   * @return platform
  **/
  @ApiModelProperty(value = "Platform hosting this deployment.")
  public DeploymentDetailsPlatform getPlatform() {
    return platform;
  }

  public void setPlatform(DeploymentDetailsPlatform platform) {
    this.platform = platform;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeployableDeploymentDetails deployableDeploymentDetails = (DeployableDeploymentDetails) o;
    return Objects.equals(this.userEmail, deployableDeploymentDetails.userEmail) &&
        Objects.equals(this.deployTime, deployableDeploymentDetails.deployTime) &&
        Objects.equals(this.undeployTime, deployableDeploymentDetails.undeployTime) &&
        Objects.equals(this.config, deployableDeploymentDetails.config) &&
        Objects.equals(this.address, deployableDeploymentDetails.address) &&
        Objects.equals(this.resourceUri, deployableDeploymentDetails.resourceUri) &&
        Objects.equals(this.platform, deployableDeploymentDetails.platform);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userEmail, deployTime, undeployTime, config, address, resourceUri, platform);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeployableDeploymentDetails {\n");
    
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    deployTime: ").append(toIndentedString(deployTime)).append("\n");
    sb.append("    undeployTime: ").append(toIndentedString(undeployTime)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    resourceUri: ").append(toIndentedString(resourceUri)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

