/*
 * Grafeas API
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.grafeas.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.grafeas.model.LongrunningOperation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Provides information about the scan status of a discovered resource.
 */
@ApiModel(description = "Provides information about the scan status of a discovered resource.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-04T13:20:14.121-07:00")
public class DiscoveryDiscoveredDetails {
  @SerializedName("operation")
  private LongrunningOperation operation = null;

  public DiscoveryDiscoveredDetails operation(LongrunningOperation operation) {
    this.operation = operation;
    return this;
  }

   /**
   * Output only. An operation that indicates the status of the current scan.
   * @return operation
  **/
  @ApiModelProperty(value = "Output only. An operation that indicates the status of the current scan.")
  public LongrunningOperation getOperation() {
    return operation;
  }

  public void setOperation(LongrunningOperation operation) {
    this.operation = operation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiscoveryDiscoveredDetails discoveryDiscoveredDetails = (DiscoveryDiscoveredDetails) o;
    return Objects.equals(this.operation, discoveryDiscoveredDetails.operation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiscoveryDiscoveredDetails {\n");
    
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

