/*
 * Grafeas API
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.grafeas.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.grafeas.model.ProtobufAny;
import io.grafeas.model.RpcStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * This resource represents a long-running operation that is the result of a network API call.
 */
@ApiModel(description = "This resource represents a long-running operation that is the result of a network API call.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-04T13:20:14.121-07:00")
public class LongrunningOperation {
  @SerializedName("name")
  private String name = null;

  @SerializedName("metadata")
  private ProtobufAny metadata = null;

  @SerializedName("done")
  private Boolean done = null;

  @SerializedName("error")
  private RpcStatus error = null;

  @SerializedName("response")
  private ProtobufAny response = null;

  public LongrunningOperation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the &#x60;name&#x60; should have the format of &#x60;operations/some/unique/name&#x60;.
   * @return name
  **/
  @ApiModelProperty(value = "The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should have the format of `operations/some/unique/name`.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LongrunningOperation metadata(ProtobufAny metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Service-specific metadata associated with the operation.  It typically contains progress information and common metadata such as create time. Some services might not provide such metadata.  Any method that returns a long-running operation should document the metadata type, if any.
   * @return metadata
  **/
  @ApiModelProperty(value = "Service-specific metadata associated with the operation.  It typically contains progress information and common metadata such as create time. Some services might not provide such metadata.  Any method that returns a long-running operation should document the metadata type, if any.")
  public ProtobufAny getMetadata() {
    return metadata;
  }

  public void setMetadata(ProtobufAny metadata) {
    this.metadata = metadata;
  }

  public LongrunningOperation done(Boolean done) {
    this.done = done;
    return this;
  }

   /**
   * If the value is &#x60;false&#x60;, it means the operation is still in progress. If true, the operation is completed, and either &#x60;error&#x60; or &#x60;response&#x60; is available.
   * @return done
  **/
  @ApiModelProperty(value = "If the value is `false`, it means the operation is still in progress. If true, the operation is completed, and either `error` or `response` is available.")
  public Boolean isDone() {
    return done;
  }

  public void setDone(Boolean done) {
    this.done = done;
  }

  public LongrunningOperation error(RpcStatus error) {
    this.error = error;
    return this;
  }

   /**
   * The error result of the operation in case of failure or cancellation.
   * @return error
  **/
  @ApiModelProperty(value = "The error result of the operation in case of failure or cancellation.")
  public RpcStatus getError() {
    return error;
  }

  public void setError(RpcStatus error) {
    this.error = error;
  }

  public LongrunningOperation response(ProtobufAny response) {
    this.response = response;
    return this;
  }

   /**
   * The normal response of the operation in case of success.  If the original method returns no data on success, such as &#x60;Delete&#x60;, the response is &#x60;google.protobuf.Empty&#x60;.  If the original method is standard &#x60;Get&#x60;/&#x60;Create&#x60;/&#x60;Update&#x60;, the response should be the resource.  For other methods, the response should have the type &#x60;XxxResponse&#x60;, where &#x60;Xxx&#x60; is the original method name.  For example, if the original method name is &#x60;TakeSnapshot()&#x60;, the inferred response type is &#x60;TakeSnapshotResponse&#x60;.
   * @return response
  **/
  @ApiModelProperty(value = "The normal response of the operation in case of success.  If the original method returns no data on success, such as `Delete`, the response is `google.protobuf.Empty`.  If the original method is standard `Get`/`Create`/`Update`, the response should be the resource.  For other methods, the response should have the type `XxxResponse`, where `Xxx` is the original method name.  For example, if the original method name is `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.")
  public ProtobufAny getResponse() {
    return response;
  }

  public void setResponse(ProtobufAny response) {
    this.response = response;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LongrunningOperation longrunningOperation = (LongrunningOperation) o;
    return Objects.equals(this.name, longrunningOperation.name) &&
        Objects.equals(this.metadata, longrunningOperation.metadata) &&
        Objects.equals(this.done, longrunningOperation.done) &&
        Objects.equals(this.error, longrunningOperation.error) &&
        Objects.equals(this.response, longrunningOperation.response);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, metadata, done, error, response);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LongrunningOperation {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    done: ").append(toIndentedString(done)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

