/*
 * Grafeas API
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.grafeas.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.grafeas.model.ApiPackageManagerLocation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * This represents how a particular software package may be installed on a system.
 */
@ApiModel(description = "This represents how a particular software package may be installed on a system.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-04T13:20:14.121-07:00")
public class PackageManagerInstallationDetails {
  @SerializedName("name")
  private String name = null;

  @SerializedName("location")
  private List<ApiPackageManagerLocation> location = null;

  public PackageManagerInstallationDetails name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Output only. The name of the installed package.
   * @return name
  **/
  @ApiModelProperty(value = "Output only. The name of the installed package.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PackageManagerInstallationDetails location(List<ApiPackageManagerLocation> location) {
    this.location = location;
    return this;
  }

  public PackageManagerInstallationDetails addLocationItem(ApiPackageManagerLocation locationItem) {
    if (this.location == null) {
      this.location = new ArrayList<ApiPackageManagerLocation>();
    }
    this.location.add(locationItem);
    return this;
  }

   /**
   * All of the places within the filesystem versions of this package have been found.
   * @return location
  **/
  @ApiModelProperty(value = "All of the places within the filesystem versions of this package have been found.")
  public List<ApiPackageManagerLocation> getLocation() {
    return location;
  }

  public void setLocation(List<ApiPackageManagerLocation> location) {
    this.location = location;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageManagerInstallationDetails packageManagerInstallationDetails = (PackageManagerInstallationDetails) o;
    return Objects.equals(this.name, packageManagerInstallationDetails.name) &&
        Objects.equals(this.location, packageManagerInstallationDetails.location);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, location);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackageManagerInstallationDetails {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

