/*
 * Grafeas API
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.grafeas.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.grafeas.model.PackageManagerDistribution;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * This represents a particular package that is distributed over various channels. e.g. glibc (aka libc6) is distributed by many, at various versions.
 */
@ApiModel(description = "This represents a particular package that is distributed over various channels. e.g. glibc (aka libc6) is distributed by many, at various versions.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-04T13:20:14.121-07:00")
public class PackageManagerPackage {
  @SerializedName("name")
  private String name = null;

  @SerializedName("distribution")
  private List<PackageManagerDistribution> distribution = null;

  public PackageManagerPackage name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the package.
   * @return name
  **/
  @ApiModelProperty(value = "The name of the package.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PackageManagerPackage distribution(List<PackageManagerDistribution> distribution) {
    this.distribution = distribution;
    return this;
  }

  public PackageManagerPackage addDistributionItem(PackageManagerDistribution distributionItem) {
    if (this.distribution == null) {
      this.distribution = new ArrayList<PackageManagerDistribution>();
    }
    this.distribution.add(distributionItem);
    return this;
  }

   /**
   * The various channels by which a package is distributed.
   * @return distribution
  **/
  @ApiModelProperty(value = "The various channels by which a package is distributed.")
  public List<PackageManagerDistribution> getDistribution() {
    return distribution;
  }

  public void setDistribution(List<PackageManagerDistribution> distribution) {
    this.distribution = distribution;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageManagerPackage packageManagerPackage = (PackageManagerPackage) o;
    return Objects.equals(this.name, packageManagerPackage.name) &&
        Objects.equals(this.distribution, packageManagerPackage.distribution);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, distribution);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackageManagerPackage {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    distribution: ").append(toIndentedString(distribution)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

